name: Chocolatine
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MIRROR_URL: git@github.com:CestAberrant/devops.git

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY}}
  

